// Generated by gencpp from file common_msgs_gl/GetBool.msg
// DO NOT EDIT!


#ifndef COMMON_MSGS_GL_MESSAGE_GETBOOL_H
#define COMMON_MSGS_GL_MESSAGE_GETBOOL_H

#include <ros/service_traits.h>


#include <common_msgs_gl/GetBoolRequest.h>
#include <common_msgs_gl/GetBoolResponse.h>


namespace common_msgs_gl
{

struct GetBool
{

typedef GetBoolRequest Request;
typedef GetBoolResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GetBool
} // namespace common_msgs_gl


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::common_msgs_gl::GetBool > {
  static const char* value()
  {
    return "8b94c1b53db61fb6aed406028ad6332a";
  }

  static const char* value(const ::common_msgs_gl::GetBool&) { return value(); }
};

template<>
struct DataType< ::common_msgs_gl::GetBool > {
  static const char* value()
  {
    return "common_msgs_gl/GetBool";
  }

  static const char* value(const ::common_msgs_gl::GetBool&) { return value(); }
};


// service_traits::MD5Sum< ::common_msgs_gl::GetBoolRequest> should match 
// service_traits::MD5Sum< ::common_msgs_gl::GetBool > 
template<>
struct MD5Sum< ::common_msgs_gl::GetBoolRequest>
{
  static const char* value()
  {
    return MD5Sum< ::common_msgs_gl::GetBool >::value();
  }
  static const char* value(const ::common_msgs_gl::GetBoolRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::common_msgs_gl::GetBoolRequest> should match 
// service_traits::DataType< ::common_msgs_gl::GetBool > 
template<>
struct DataType< ::common_msgs_gl::GetBoolRequest>
{
  static const char* value()
  {
    return DataType< ::common_msgs_gl::GetBool >::value();
  }
  static const char* value(const ::common_msgs_gl::GetBoolRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::common_msgs_gl::GetBoolResponse> should match 
// service_traits::MD5Sum< ::common_msgs_gl::GetBool > 
template<>
struct MD5Sum< ::common_msgs_gl::GetBoolResponse>
{
  static const char* value()
  {
    return MD5Sum< ::common_msgs_gl::GetBool >::value();
  }
  static const char* value(const ::common_msgs_gl::GetBoolResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::common_msgs_gl::GetBoolResponse> should match 
// service_traits::DataType< ::common_msgs_gl::GetBool > 
template<>
struct DataType< ::common_msgs_gl::GetBoolResponse>
{
  static const char* value()
  {
    return DataType< ::common_msgs_gl::GetBool >::value();
  }
  static const char* value(const ::common_msgs_gl::GetBoolResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // COMMON_MSGS_GL_MESSAGE_GETBOOL_H
