// Generated by gencpp from file common_msgs_gl/GetBoolArray.msg
// DO NOT EDIT!


#ifndef COMMON_MSGS_GL_MESSAGE_GETBOOLARRAY_H
#define COMMON_MSGS_GL_MESSAGE_GETBOOLARRAY_H

#include <ros/service_traits.h>


#include <common_msgs_gl/GetBoolArrayRequest.h>
#include <common_msgs_gl/GetBoolArrayResponse.h>


namespace common_msgs_gl
{

struct GetBoolArray
{

typedef GetBoolArrayRequest Request;
typedef GetBoolArrayResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GetBoolArray
} // namespace common_msgs_gl


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::common_msgs_gl::GetBoolArray > {
  static const char* value()
  {
    return "403a16d9294b908e45c67a6f3c3a5b27";
  }

  static const char* value(const ::common_msgs_gl::GetBoolArray&) { return value(); }
};

template<>
struct DataType< ::common_msgs_gl::GetBoolArray > {
  static const char* value()
  {
    return "common_msgs_gl/GetBoolArray";
  }

  static const char* value(const ::common_msgs_gl::GetBoolArray&) { return value(); }
};


// service_traits::MD5Sum< ::common_msgs_gl::GetBoolArrayRequest> should match 
// service_traits::MD5Sum< ::common_msgs_gl::GetBoolArray > 
template<>
struct MD5Sum< ::common_msgs_gl::GetBoolArrayRequest>
{
  static const char* value()
  {
    return MD5Sum< ::common_msgs_gl::GetBoolArray >::value();
  }
  static const char* value(const ::common_msgs_gl::GetBoolArrayRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::common_msgs_gl::GetBoolArrayRequest> should match 
// service_traits::DataType< ::common_msgs_gl::GetBoolArray > 
template<>
struct DataType< ::common_msgs_gl::GetBoolArrayRequest>
{
  static const char* value()
  {
    return DataType< ::common_msgs_gl::GetBoolArray >::value();
  }
  static const char* value(const ::common_msgs_gl::GetBoolArrayRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::common_msgs_gl::GetBoolArrayResponse> should match 
// service_traits::MD5Sum< ::common_msgs_gl::GetBoolArray > 
template<>
struct MD5Sum< ::common_msgs_gl::GetBoolArrayResponse>
{
  static const char* value()
  {
    return MD5Sum< ::common_msgs_gl::GetBoolArray >::value();
  }
  static const char* value(const ::common_msgs_gl::GetBoolArrayResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::common_msgs_gl::GetBoolArrayResponse> should match 
// service_traits::DataType< ::common_msgs_gl::GetBoolArray > 
template<>
struct DataType< ::common_msgs_gl::GetBoolArrayResponse>
{
  static const char* value()
  {
    return DataType< ::common_msgs_gl::GetBoolArray >::value();
  }
  static const char* value(const ::common_msgs_gl::GetBoolArrayResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // COMMON_MSGS_GL_MESSAGE_GETBOOLARRAY_H
