// Generated by gencpp from file common_msgs_gl/GetDoubleArray.msg
// DO NOT EDIT!


#ifndef COMMON_MSGS_GL_MESSAGE_GETDOUBLEARRAY_H
#define COMMON_MSGS_GL_MESSAGE_GETDOUBLEARRAY_H

#include <ros/service_traits.h>


#include <common_msgs_gl/GetDoubleArrayRequest.h>
#include <common_msgs_gl/GetDoubleArrayResponse.h>


namespace common_msgs_gl
{

struct GetDoubleArray
{

typedef GetDoubleArrayRequest Request;
typedef GetDoubleArrayResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GetDoubleArray
} // namespace common_msgs_gl


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::common_msgs_gl::GetDoubleArray > {
  static const char* value()
  {
    return "788898178a3da2c3718461eecda8f714";
  }

  static const char* value(const ::common_msgs_gl::GetDoubleArray&) { return value(); }
};

template<>
struct DataType< ::common_msgs_gl::GetDoubleArray > {
  static const char* value()
  {
    return "common_msgs_gl/GetDoubleArray";
  }

  static const char* value(const ::common_msgs_gl::GetDoubleArray&) { return value(); }
};


// service_traits::MD5Sum< ::common_msgs_gl::GetDoubleArrayRequest> should match 
// service_traits::MD5Sum< ::common_msgs_gl::GetDoubleArray > 
template<>
struct MD5Sum< ::common_msgs_gl::GetDoubleArrayRequest>
{
  static const char* value()
  {
    return MD5Sum< ::common_msgs_gl::GetDoubleArray >::value();
  }
  static const char* value(const ::common_msgs_gl::GetDoubleArrayRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::common_msgs_gl::GetDoubleArrayRequest> should match 
// service_traits::DataType< ::common_msgs_gl::GetDoubleArray > 
template<>
struct DataType< ::common_msgs_gl::GetDoubleArrayRequest>
{
  static const char* value()
  {
    return DataType< ::common_msgs_gl::GetDoubleArray >::value();
  }
  static const char* value(const ::common_msgs_gl::GetDoubleArrayRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::common_msgs_gl::GetDoubleArrayResponse> should match 
// service_traits::MD5Sum< ::common_msgs_gl::GetDoubleArray > 
template<>
struct MD5Sum< ::common_msgs_gl::GetDoubleArrayResponse>
{
  static const char* value()
  {
    return MD5Sum< ::common_msgs_gl::GetDoubleArray >::value();
  }
  static const char* value(const ::common_msgs_gl::GetDoubleArrayResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::common_msgs_gl::GetDoubleArrayResponse> should match 
// service_traits::DataType< ::common_msgs_gl::GetDoubleArray > 
template<>
struct DataType< ::common_msgs_gl::GetDoubleArrayResponse>
{
  static const char* value()
  {
    return DataType< ::common_msgs_gl::GetDoubleArray >::value();
  }
  static const char* value(const ::common_msgs_gl::GetDoubleArrayResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // COMMON_MSGS_GL_MESSAGE_GETDOUBLEARRAY_H
