// Generated by gencpp from file common_msgs_gl/GetInt.msg
// DO NOT EDIT!


#ifndef COMMON_MSGS_GL_MESSAGE_GETINT_H
#define COMMON_MSGS_GL_MESSAGE_GETINT_H

#include <ros/service_traits.h>


#include <common_msgs_gl/GetIntRequest.h>
#include <common_msgs_gl/GetIntResponse.h>


namespace common_msgs_gl
{

struct GetInt
{

typedef GetIntRequest Request;
typedef GetIntResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GetInt
} // namespace common_msgs_gl


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::common_msgs_gl::GetInt > {
  static const char* value()
  {
    return "da5909fbe378aeaf85e547e830cc1bb7";
  }

  static const char* value(const ::common_msgs_gl::GetInt&) { return value(); }
};

template<>
struct DataType< ::common_msgs_gl::GetInt > {
  static const char* value()
  {
    return "common_msgs_gl/GetInt";
  }

  static const char* value(const ::common_msgs_gl::GetInt&) { return value(); }
};


// service_traits::MD5Sum< ::common_msgs_gl::GetIntRequest> should match 
// service_traits::MD5Sum< ::common_msgs_gl::GetInt > 
template<>
struct MD5Sum< ::common_msgs_gl::GetIntRequest>
{
  static const char* value()
  {
    return MD5Sum< ::common_msgs_gl::GetInt >::value();
  }
  static const char* value(const ::common_msgs_gl::GetIntRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::common_msgs_gl::GetIntRequest> should match 
// service_traits::DataType< ::common_msgs_gl::GetInt > 
template<>
struct DataType< ::common_msgs_gl::GetIntRequest>
{
  static const char* value()
  {
    return DataType< ::common_msgs_gl::GetInt >::value();
  }
  static const char* value(const ::common_msgs_gl::GetIntRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::common_msgs_gl::GetIntResponse> should match 
// service_traits::MD5Sum< ::common_msgs_gl::GetInt > 
template<>
struct MD5Sum< ::common_msgs_gl::GetIntResponse>
{
  static const char* value()
  {
    return MD5Sum< ::common_msgs_gl::GetInt >::value();
  }
  static const char* value(const ::common_msgs_gl::GetIntResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::common_msgs_gl::GetIntResponse> should match 
// service_traits::DataType< ::common_msgs_gl::GetInt > 
template<>
struct DataType< ::common_msgs_gl::GetIntResponse>
{
  static const char* value()
  {
    return DataType< ::common_msgs_gl::GetInt >::value();
  }
  static const char* value(const ::common_msgs_gl::GetIntResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // COMMON_MSGS_GL_MESSAGE_GETINT_H
