// Generated by gencpp from file common_msgs_gl/GetString.msg
// DO NOT EDIT!


#ifndef COMMON_MSGS_GL_MESSAGE_GETSTRING_H
#define COMMON_MSGS_GL_MESSAGE_GETSTRING_H

#include <ros/service_traits.h>


#include <common_msgs_gl/GetStringRequest.h>
#include <common_msgs_gl/GetStringResponse.h>


namespace common_msgs_gl
{

struct GetString
{

typedef GetStringRequest Request;
typedef GetStringResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GetString
} // namespace common_msgs_gl


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::common_msgs_gl::GetString > {
  static const char* value()
  {
    return "992ce8a1687cec8c8bd883ec73ca41d1";
  }

  static const char* value(const ::common_msgs_gl::GetString&) { return value(); }
};

template<>
struct DataType< ::common_msgs_gl::GetString > {
  static const char* value()
  {
    return "common_msgs_gl/GetString";
  }

  static const char* value(const ::common_msgs_gl::GetString&) { return value(); }
};


// service_traits::MD5Sum< ::common_msgs_gl::GetStringRequest> should match 
// service_traits::MD5Sum< ::common_msgs_gl::GetString > 
template<>
struct MD5Sum< ::common_msgs_gl::GetStringRequest>
{
  static const char* value()
  {
    return MD5Sum< ::common_msgs_gl::GetString >::value();
  }
  static const char* value(const ::common_msgs_gl::GetStringRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::common_msgs_gl::GetStringRequest> should match 
// service_traits::DataType< ::common_msgs_gl::GetString > 
template<>
struct DataType< ::common_msgs_gl::GetStringRequest>
{
  static const char* value()
  {
    return DataType< ::common_msgs_gl::GetString >::value();
  }
  static const char* value(const ::common_msgs_gl::GetStringRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::common_msgs_gl::GetStringResponse> should match 
// service_traits::MD5Sum< ::common_msgs_gl::GetString > 
template<>
struct MD5Sum< ::common_msgs_gl::GetStringResponse>
{
  static const char* value()
  {
    return MD5Sum< ::common_msgs_gl::GetString >::value();
  }
  static const char* value(const ::common_msgs_gl::GetStringResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::common_msgs_gl::GetStringResponse> should match 
// service_traits::DataType< ::common_msgs_gl::GetString > 
template<>
struct DataType< ::common_msgs_gl::GetStringResponse>
{
  static const char* value()
  {
    return DataType< ::common_msgs_gl::GetString >::value();
  }
  static const char* value(const ::common_msgs_gl::GetStringResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // COMMON_MSGS_GL_MESSAGE_GETSTRING_H
