// Generated by gencpp from file common_msgs_gl/SendInt.msg
// DO NOT EDIT!


#ifndef COMMON_MSGS_GL_MESSAGE_SENDINT_H
#define COMMON_MSGS_GL_MESSAGE_SENDINT_H

#include <ros/service_traits.h>


#include <common_msgs_gl/SendIntRequest.h>
#include <common_msgs_gl/SendIntResponse.h>


namespace common_msgs_gl
{

struct SendInt
{

typedef SendIntRequest Request;
typedef SendIntResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SendInt
} // namespace common_msgs_gl


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::common_msgs_gl::SendInt > {
  static const char* value()
  {
    return "da5909fbe378aeaf85e547e830cc1bb7";
  }

  static const char* value(const ::common_msgs_gl::SendInt&) { return value(); }
};

template<>
struct DataType< ::common_msgs_gl::SendInt > {
  static const char* value()
  {
    return "common_msgs_gl/SendInt";
  }

  static const char* value(const ::common_msgs_gl::SendInt&) { return value(); }
};


// service_traits::MD5Sum< ::common_msgs_gl::SendIntRequest> should match 
// service_traits::MD5Sum< ::common_msgs_gl::SendInt > 
template<>
struct MD5Sum< ::common_msgs_gl::SendIntRequest>
{
  static const char* value()
  {
    return MD5Sum< ::common_msgs_gl::SendInt >::value();
  }
  static const char* value(const ::common_msgs_gl::SendIntRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::common_msgs_gl::SendIntRequest> should match 
// service_traits::DataType< ::common_msgs_gl::SendInt > 
template<>
struct DataType< ::common_msgs_gl::SendIntRequest>
{
  static const char* value()
  {
    return DataType< ::common_msgs_gl::SendInt >::value();
  }
  static const char* value(const ::common_msgs_gl::SendIntRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::common_msgs_gl::SendIntResponse> should match 
// service_traits::MD5Sum< ::common_msgs_gl::SendInt > 
template<>
struct MD5Sum< ::common_msgs_gl::SendIntResponse>
{
  static const char* value()
  {
    return MD5Sum< ::common_msgs_gl::SendInt >::value();
  }
  static const char* value(const ::common_msgs_gl::SendIntResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::common_msgs_gl::SendIntResponse> should match 
// service_traits::DataType< ::common_msgs_gl::SendInt > 
template<>
struct DataType< ::common_msgs_gl::SendIntResponse>
{
  static const char* value()
  {
    return DataType< ::common_msgs_gl::SendInt >::value();
  }
  static const char* value(const ::common_msgs_gl::SendIntResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // COMMON_MSGS_GL_MESSAGE_SENDINT_H
