// Generated by gencpp from file common_msgs_gl/SendPointArrayRequest.msg
// DO NOT EDIT!


#ifndef COMMON_MSGS_GL_MESSAGE_SENDPOINTARRAYREQUEST_H
#define COMMON_MSGS_GL_MESSAGE_SENDPOINTARRAYREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <common_msgs_gl/PointArray.h>

namespace common_msgs_gl
{
template <class ContainerAllocator>
struct SendPointArrayRequest_
{
  typedef SendPointArrayRequest_<ContainerAllocator> Type;

  SendPointArrayRequest_()
    : points()  {
    }
  SendPointArrayRequest_(const ContainerAllocator& _alloc)
    : points(_alloc)  {
  (void)_alloc;
    }



   typedef  ::common_msgs_gl::PointArray_<ContainerAllocator>  _points_type;
  _points_type points;





  typedef boost::shared_ptr< ::common_msgs_gl::SendPointArrayRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::common_msgs_gl::SendPointArrayRequest_<ContainerAllocator> const> ConstPtr;

}; // struct SendPointArrayRequest_

typedef ::common_msgs_gl::SendPointArrayRequest_<std::allocator<void> > SendPointArrayRequest;

typedef boost::shared_ptr< ::common_msgs_gl::SendPointArrayRequest > SendPointArrayRequestPtr;
typedef boost::shared_ptr< ::common_msgs_gl::SendPointArrayRequest const> SendPointArrayRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::common_msgs_gl::SendPointArrayRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::common_msgs_gl::SendPointArrayRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace common_msgs_gl

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'common_msgs_gl': ['/home/grablabadmin/workspace/Yale-OpenHand-Workshop-2018/ROS/src/common/common_msgs_gl/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::common_msgs_gl::SendPointArrayRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::common_msgs_gl::SendPointArrayRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::common_msgs_gl::SendPointArrayRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::common_msgs_gl::SendPointArrayRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::common_msgs_gl::SendPointArrayRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::common_msgs_gl::SendPointArrayRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::common_msgs_gl::SendPointArrayRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "9dbb4bd593812628a7a52a04aefa8ecb";
  }

  static const char* value(const ::common_msgs_gl::SendPointArrayRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x9dbb4bd593812628ULL;
  static const uint64_t static_value2 = 0xa7a52a04aefa8ecbULL;
};

template<class ContainerAllocator>
struct DataType< ::common_msgs_gl::SendPointArrayRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "common_msgs_gl/SendPointArrayRequest";
  }

  static const char* value(const ::common_msgs_gl::SendPointArrayRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::common_msgs_gl::SendPointArrayRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "common_msgs_gl/PointArray points\n\
\n\
================================================================================\n\
MSG: common_msgs_gl/PointArray\n\
int32[] x\n\
int32[] y\n\
";
  }

  static const char* value(const ::common_msgs_gl::SendPointArrayRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::common_msgs_gl::SendPointArrayRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.points);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SendPointArrayRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::common_msgs_gl::SendPointArrayRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::common_msgs_gl::SendPointArrayRequest_<ContainerAllocator>& v)
  {
    s << indent << "points: ";
    s << std::endl;
    Printer< ::common_msgs_gl::PointArray_<ContainerAllocator> >::stream(s, indent + "  ", v.points);
  }
};

} // namespace message_operations
} // namespace ros

#endif // COMMON_MSGS_GL_MESSAGE_SENDPOINTARRAYREQUEST_H
