// Generated by gencpp from file common_msgs_gl/SendDouble.msg
// DO NOT EDIT!


#ifndef COMMON_MSGS_GL_MESSAGE_SENDDOUBLE_H
#define COMMON_MSGS_GL_MESSAGE_SENDDOUBLE_H

#include <ros/service_traits.h>


#include <common_msgs_gl/SendDoubleRequest.h>
#include <common_msgs_gl/SendDoubleResponse.h>


namespace common_msgs_gl
{

struct SendDouble
{

typedef SendDoubleRequest Request;
typedef SendDoubleResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SendDouble
} // namespace common_msgs_gl


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::common_msgs_gl::SendDouble > {
  static const char* value()
  {
    return "fdb28210bfa9d7c91146260178d9a584";
  }

  static const char* value(const ::common_msgs_gl::SendDouble&) { return value(); }
};

template<>
struct DataType< ::common_msgs_gl::SendDouble > {
  static const char* value()
  {
    return "common_msgs_gl/SendDouble";
  }

  static const char* value(const ::common_msgs_gl::SendDouble&) { return value(); }
};


// service_traits::MD5Sum< ::common_msgs_gl::SendDoubleRequest> should match 
// service_traits::MD5Sum< ::common_msgs_gl::SendDouble > 
template<>
struct MD5Sum< ::common_msgs_gl::SendDoubleRequest>
{
  static const char* value()
  {
    return MD5Sum< ::common_msgs_gl::SendDouble >::value();
  }
  static const char* value(const ::common_msgs_gl::SendDoubleRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::common_msgs_gl::SendDoubleRequest> should match 
// service_traits::DataType< ::common_msgs_gl::SendDouble > 
template<>
struct DataType< ::common_msgs_gl::SendDoubleRequest>
{
  static const char* value()
  {
    return DataType< ::common_msgs_gl::SendDouble >::value();
  }
  static const char* value(const ::common_msgs_gl::SendDoubleRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::common_msgs_gl::SendDoubleResponse> should match 
// service_traits::MD5Sum< ::common_msgs_gl::SendDouble > 
template<>
struct MD5Sum< ::common_msgs_gl::SendDoubleResponse>
{
  static const char* value()
  {
    return MD5Sum< ::common_msgs_gl::SendDouble >::value();
  }
  static const char* value(const ::common_msgs_gl::SendDoubleResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::common_msgs_gl::SendDoubleResponse> should match 
// service_traits::DataType< ::common_msgs_gl::SendDouble > 
template<>
struct DataType< ::common_msgs_gl::SendDoubleResponse>
{
  static const char* value()
  {
    return DataType< ::common_msgs_gl::SendDouble >::value();
  }
  static const char* value(const ::common_msgs_gl::SendDoubleResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // COMMON_MSGS_GL_MESSAGE_SENDDOUBLE_H
