// Generated by gencpp from file common_msgs_gl/SendDoubleArrayReceiveDouble.msg
// DO NOT EDIT!


#ifndef COMMON_MSGS_GL_MESSAGE_SENDDOUBLEARRAYRECEIVEDOUBLE_H
#define COMMON_MSGS_GL_MESSAGE_SENDDOUBLEARRAYRECEIVEDOUBLE_H

#include <ros/service_traits.h>


#include <common_msgs_gl/SendDoubleArrayReceiveDoubleRequest.h>
#include <common_msgs_gl/SendDoubleArrayReceiveDoubleResponse.h>


namespace common_msgs_gl
{

struct SendDoubleArrayReceiveDouble
{

typedef SendDoubleArrayReceiveDoubleRequest Request;
typedef SendDoubleArrayReceiveDoubleResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SendDoubleArrayReceiveDouble
} // namespace common_msgs_gl


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::common_msgs_gl::SendDoubleArrayReceiveDouble > {
  static const char* value()
  {
    return "b748ef2ada544bd1cd84f38aa7adb516";
  }

  static const char* value(const ::common_msgs_gl::SendDoubleArrayReceiveDouble&) { return value(); }
};

template<>
struct DataType< ::common_msgs_gl::SendDoubleArrayReceiveDouble > {
  static const char* value()
  {
    return "common_msgs_gl/SendDoubleArrayReceiveDouble";
  }

  static const char* value(const ::common_msgs_gl::SendDoubleArrayReceiveDouble&) { return value(); }
};


// service_traits::MD5Sum< ::common_msgs_gl::SendDoubleArrayReceiveDoubleRequest> should match 
// service_traits::MD5Sum< ::common_msgs_gl::SendDoubleArrayReceiveDouble > 
template<>
struct MD5Sum< ::common_msgs_gl::SendDoubleArrayReceiveDoubleRequest>
{
  static const char* value()
  {
    return MD5Sum< ::common_msgs_gl::SendDoubleArrayReceiveDouble >::value();
  }
  static const char* value(const ::common_msgs_gl::SendDoubleArrayReceiveDoubleRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::common_msgs_gl::SendDoubleArrayReceiveDoubleRequest> should match 
// service_traits::DataType< ::common_msgs_gl::SendDoubleArrayReceiveDouble > 
template<>
struct DataType< ::common_msgs_gl::SendDoubleArrayReceiveDoubleRequest>
{
  static const char* value()
  {
    return DataType< ::common_msgs_gl::SendDoubleArrayReceiveDouble >::value();
  }
  static const char* value(const ::common_msgs_gl::SendDoubleArrayReceiveDoubleRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::common_msgs_gl::SendDoubleArrayReceiveDoubleResponse> should match 
// service_traits::MD5Sum< ::common_msgs_gl::SendDoubleArrayReceiveDouble > 
template<>
struct MD5Sum< ::common_msgs_gl::SendDoubleArrayReceiveDoubleResponse>
{
  static const char* value()
  {
    return MD5Sum< ::common_msgs_gl::SendDoubleArrayReceiveDouble >::value();
  }
  static const char* value(const ::common_msgs_gl::SendDoubleArrayReceiveDoubleResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::common_msgs_gl::SendDoubleArrayReceiveDoubleResponse> should match 
// service_traits::DataType< ::common_msgs_gl::SendDoubleArrayReceiveDouble > 
template<>
struct DataType< ::common_msgs_gl::SendDoubleArrayReceiveDoubleResponse>
{
  static const char* value()
  {
    return DataType< ::common_msgs_gl::SendDoubleArrayReceiveDouble >::value();
  }
  static const char* value(const ::common_msgs_gl::SendDoubleArrayReceiveDoubleResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // COMMON_MSGS_GL_MESSAGE_SENDDOUBLEARRAYRECEIVEDOUBLE_H
