// Generated by gencpp from file common_msgs_gl/SendDoubleArrayReceiveIntDouble.msg
// DO NOT EDIT!


#ifndef COMMON_MSGS_GL_MESSAGE_SENDDOUBLEARRAYRECEIVEINTDOUBLE_H
#define COMMON_MSGS_GL_MESSAGE_SENDDOUBLEARRAYRECEIVEINTDOUBLE_H

#include <ros/service_traits.h>


#include <common_msgs_gl/SendDoubleArrayReceiveIntDoubleRequest.h>
#include <common_msgs_gl/SendDoubleArrayReceiveIntDoubleResponse.h>


namespace common_msgs_gl
{

struct SendDoubleArrayReceiveIntDouble
{

typedef SendDoubleArrayReceiveIntDoubleRequest Request;
typedef SendDoubleArrayReceiveIntDoubleResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SendDoubleArrayReceiveIntDouble
} // namespace common_msgs_gl


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::common_msgs_gl::SendDoubleArrayReceiveIntDouble > {
  static const char* value()
  {
    return "ca79180c13450f9faa7d51f5b725d04b";
  }

  static const char* value(const ::common_msgs_gl::SendDoubleArrayReceiveIntDouble&) { return value(); }
};

template<>
struct DataType< ::common_msgs_gl::SendDoubleArrayReceiveIntDouble > {
  static const char* value()
  {
    return "common_msgs_gl/SendDoubleArrayReceiveIntDouble";
  }

  static const char* value(const ::common_msgs_gl::SendDoubleArrayReceiveIntDouble&) { return value(); }
};


// service_traits::MD5Sum< ::common_msgs_gl::SendDoubleArrayReceiveIntDoubleRequest> should match 
// service_traits::MD5Sum< ::common_msgs_gl::SendDoubleArrayReceiveIntDouble > 
template<>
struct MD5Sum< ::common_msgs_gl::SendDoubleArrayReceiveIntDoubleRequest>
{
  static const char* value()
  {
    return MD5Sum< ::common_msgs_gl::SendDoubleArrayReceiveIntDouble >::value();
  }
  static const char* value(const ::common_msgs_gl::SendDoubleArrayReceiveIntDoubleRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::common_msgs_gl::SendDoubleArrayReceiveIntDoubleRequest> should match 
// service_traits::DataType< ::common_msgs_gl::SendDoubleArrayReceiveIntDouble > 
template<>
struct DataType< ::common_msgs_gl::SendDoubleArrayReceiveIntDoubleRequest>
{
  static const char* value()
  {
    return DataType< ::common_msgs_gl::SendDoubleArrayReceiveIntDouble >::value();
  }
  static const char* value(const ::common_msgs_gl::SendDoubleArrayReceiveIntDoubleRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::common_msgs_gl::SendDoubleArrayReceiveIntDoubleResponse> should match 
// service_traits::MD5Sum< ::common_msgs_gl::SendDoubleArrayReceiveIntDouble > 
template<>
struct MD5Sum< ::common_msgs_gl::SendDoubleArrayReceiveIntDoubleResponse>
{
  static const char* value()
  {
    return MD5Sum< ::common_msgs_gl::SendDoubleArrayReceiveIntDouble >::value();
  }
  static const char* value(const ::common_msgs_gl::SendDoubleArrayReceiveIntDoubleResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::common_msgs_gl::SendDoubleArrayReceiveIntDoubleResponse> should match 
// service_traits::DataType< ::common_msgs_gl::SendDoubleArrayReceiveIntDouble > 
template<>
struct DataType< ::common_msgs_gl::SendDoubleArrayReceiveIntDoubleResponse>
{
  static const char* value()
  {
    return DataType< ::common_msgs_gl::SendDoubleArrayReceiveIntDouble >::value();
  }
  static const char* value(const ::common_msgs_gl::SendDoubleArrayReceiveIntDoubleResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // COMMON_MSGS_GL_MESSAGE_SENDDOUBLEARRAYRECEIVEINTDOUBLE_H
