// Generated by gencpp from file common_msgs_gl/SendPointArray.msg
// DO NOT EDIT!


#ifndef COMMON_MSGS_GL_MESSAGE_SENDPOINTARRAY_H
#define COMMON_MSGS_GL_MESSAGE_SENDPOINTARRAY_H

#include <ros/service_traits.h>


#include <common_msgs_gl/SendPointArrayRequest.h>
#include <common_msgs_gl/SendPointArrayResponse.h>


namespace common_msgs_gl
{

struct SendPointArray
{

typedef SendPointArrayRequest Request;
typedef SendPointArrayResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SendPointArray
} // namespace common_msgs_gl


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::common_msgs_gl::SendPointArray > {
  static const char* value()
  {
    return "9dbb4bd593812628a7a52a04aefa8ecb";
  }

  static const char* value(const ::common_msgs_gl::SendPointArray&) { return value(); }
};

template<>
struct DataType< ::common_msgs_gl::SendPointArray > {
  static const char* value()
  {
    return "common_msgs_gl/SendPointArray";
  }

  static const char* value(const ::common_msgs_gl::SendPointArray&) { return value(); }
};


// service_traits::MD5Sum< ::common_msgs_gl::SendPointArrayRequest> should match 
// service_traits::MD5Sum< ::common_msgs_gl::SendPointArray > 
template<>
struct MD5Sum< ::common_msgs_gl::SendPointArrayRequest>
{
  static const char* value()
  {
    return MD5Sum< ::common_msgs_gl::SendPointArray >::value();
  }
  static const char* value(const ::common_msgs_gl::SendPointArrayRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::common_msgs_gl::SendPointArrayRequest> should match 
// service_traits::DataType< ::common_msgs_gl::SendPointArray > 
template<>
struct DataType< ::common_msgs_gl::SendPointArrayRequest>
{
  static const char* value()
  {
    return DataType< ::common_msgs_gl::SendPointArray >::value();
  }
  static const char* value(const ::common_msgs_gl::SendPointArrayRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::common_msgs_gl::SendPointArrayResponse> should match 
// service_traits::MD5Sum< ::common_msgs_gl::SendPointArray > 
template<>
struct MD5Sum< ::common_msgs_gl::SendPointArrayResponse>
{
  static const char* value()
  {
    return MD5Sum< ::common_msgs_gl::SendPointArray >::value();
  }
  static const char* value(const ::common_msgs_gl::SendPointArrayResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::common_msgs_gl::SendPointArrayResponse> should match 
// service_traits::DataType< ::common_msgs_gl::SendPointArray > 
template<>
struct DataType< ::common_msgs_gl::SendPointArrayResponse>
{
  static const char* value()
  {
    return DataType< ::common_msgs_gl::SendPointArray >::value();
  }
  static const char* value(const ::common_msgs_gl::SendPointArrayResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // COMMON_MSGS_GL_MESSAGE_SENDPOINTARRAY_H
