// Generated by gencpp from file common_msgs_gl/SendDoubleArray.msg
// DO NOT EDIT!


#ifndef COMMON_MSGS_GL_MESSAGE_SENDDOUBLEARRAY_H
#define COMMON_MSGS_GL_MESSAGE_SENDDOUBLEARRAY_H

#include <ros/service_traits.h>


#include <common_msgs_gl/SendDoubleArrayRequest.h>
#include <common_msgs_gl/SendDoubleArrayResponse.h>


namespace common_msgs_gl
{

struct SendDoubleArray
{

typedef SendDoubleArrayRequest Request;
typedef SendDoubleArrayResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SendDoubleArray
} // namespace common_msgs_gl


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::common_msgs_gl::SendDoubleArray > {
  static const char* value()
  {
    return "788898178a3da2c3718461eecda8f714";
  }

  static const char* value(const ::common_msgs_gl::SendDoubleArray&) { return value(); }
};

template<>
struct DataType< ::common_msgs_gl::SendDoubleArray > {
  static const char* value()
  {
    return "common_msgs_gl/SendDoubleArray";
  }

  static const char* value(const ::common_msgs_gl::SendDoubleArray&) { return value(); }
};


// service_traits::MD5Sum< ::common_msgs_gl::SendDoubleArrayRequest> should match 
// service_traits::MD5Sum< ::common_msgs_gl::SendDoubleArray > 
template<>
struct MD5Sum< ::common_msgs_gl::SendDoubleArrayRequest>
{
  static const char* value()
  {
    return MD5Sum< ::common_msgs_gl::SendDoubleArray >::value();
  }
  static const char* value(const ::common_msgs_gl::SendDoubleArrayRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::common_msgs_gl::SendDoubleArrayRequest> should match 
// service_traits::DataType< ::common_msgs_gl::SendDoubleArray > 
template<>
struct DataType< ::common_msgs_gl::SendDoubleArrayRequest>
{
  static const char* value()
  {
    return DataType< ::common_msgs_gl::SendDoubleArray >::value();
  }
  static const char* value(const ::common_msgs_gl::SendDoubleArrayRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::common_msgs_gl::SendDoubleArrayResponse> should match 
// service_traits::MD5Sum< ::common_msgs_gl::SendDoubleArray > 
template<>
struct MD5Sum< ::common_msgs_gl::SendDoubleArrayResponse>
{
  static const char* value()
  {
    return MD5Sum< ::common_msgs_gl::SendDoubleArray >::value();
  }
  static const char* value(const ::common_msgs_gl::SendDoubleArrayResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::common_msgs_gl::SendDoubleArrayResponse> should match 
// service_traits::DataType< ::common_msgs_gl::SendDoubleArray > 
template<>
struct DataType< ::common_msgs_gl::SendDoubleArrayResponse>
{
  static const char* value()
  {
    return DataType< ::common_msgs_gl::SendDoubleArray >::value();
  }
  static const char* value(const ::common_msgs_gl::SendDoubleArrayResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // COMMON_MSGS_GL_MESSAGE_SENDDOUBLEARRAY_H
