// Generated by gencpp from file common_msgs_gl/SendDoubleArrayReceiveInt.msg
// DO NOT EDIT!


#ifndef COMMON_MSGS_GL_MESSAGE_SENDDOUBLEARRAYRECEIVEINT_H
#define COMMON_MSGS_GL_MESSAGE_SENDDOUBLEARRAYRECEIVEINT_H

#include <ros/service_traits.h>


#include <common_msgs_gl/SendDoubleArrayReceiveIntRequest.h>
#include <common_msgs_gl/SendDoubleArrayReceiveIntResponse.h>


namespace common_msgs_gl
{

struct SendDoubleArrayReceiveInt
{

typedef SendDoubleArrayReceiveIntRequest Request;
typedef SendDoubleArrayReceiveIntResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SendDoubleArrayReceiveInt
} // namespace common_msgs_gl


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::common_msgs_gl::SendDoubleArrayReceiveInt > {
  static const char* value()
  {
    return "e192e1ed09b2c0baf14ccafbc9c08e6c";
  }

  static const char* value(const ::common_msgs_gl::SendDoubleArrayReceiveInt&) { return value(); }
};

template<>
struct DataType< ::common_msgs_gl::SendDoubleArrayReceiveInt > {
  static const char* value()
  {
    return "common_msgs_gl/SendDoubleArrayReceiveInt";
  }

  static const char* value(const ::common_msgs_gl::SendDoubleArrayReceiveInt&) { return value(); }
};


// service_traits::MD5Sum< ::common_msgs_gl::SendDoubleArrayReceiveIntRequest> should match 
// service_traits::MD5Sum< ::common_msgs_gl::SendDoubleArrayReceiveInt > 
template<>
struct MD5Sum< ::common_msgs_gl::SendDoubleArrayReceiveIntRequest>
{
  static const char* value()
  {
    return MD5Sum< ::common_msgs_gl::SendDoubleArrayReceiveInt >::value();
  }
  static const char* value(const ::common_msgs_gl::SendDoubleArrayReceiveIntRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::common_msgs_gl::SendDoubleArrayReceiveIntRequest> should match 
// service_traits::DataType< ::common_msgs_gl::SendDoubleArrayReceiveInt > 
template<>
struct DataType< ::common_msgs_gl::SendDoubleArrayReceiveIntRequest>
{
  static const char* value()
  {
    return DataType< ::common_msgs_gl::SendDoubleArrayReceiveInt >::value();
  }
  static const char* value(const ::common_msgs_gl::SendDoubleArrayReceiveIntRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::common_msgs_gl::SendDoubleArrayReceiveIntResponse> should match 
// service_traits::MD5Sum< ::common_msgs_gl::SendDoubleArrayReceiveInt > 
template<>
struct MD5Sum< ::common_msgs_gl::SendDoubleArrayReceiveIntResponse>
{
  static const char* value()
  {
    return MD5Sum< ::common_msgs_gl::SendDoubleArrayReceiveInt >::value();
  }
  static const char* value(const ::common_msgs_gl::SendDoubleArrayReceiveIntResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::common_msgs_gl::SendDoubleArrayReceiveIntResponse> should match 
// service_traits::DataType< ::common_msgs_gl::SendDoubleArrayReceiveInt > 
template<>
struct DataType< ::common_msgs_gl::SendDoubleArrayReceiveIntResponse>
{
  static const char* value()
  {
    return DataType< ::common_msgs_gl::SendDoubleArrayReceiveInt >::value();
  }
  static const char* value(const ::common_msgs_gl::SendDoubleArrayReceiveIntResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // COMMON_MSGS_GL_MESSAGE_SENDDOUBLEARRAYRECEIVEINT_H
