// Generated by gencpp from file common_msgs_gl/SendDoubleArrayReceiveDoubleArray.msg
// DO NOT EDIT!


#ifndef COMMON_MSGS_GL_MESSAGE_SENDDOUBLEARRAYRECEIVEDOUBLEARRAY_H
#define COMMON_MSGS_GL_MESSAGE_SENDDOUBLEARRAYRECEIVEDOUBLEARRAY_H

#include <ros/service_traits.h>


#include <common_msgs_gl/SendDoubleArrayReceiveDoubleArrayRequest.h>
#include <common_msgs_gl/SendDoubleArrayReceiveDoubleArrayResponse.h>


namespace common_msgs_gl
{

struct SendDoubleArrayReceiveDoubleArray
{

typedef SendDoubleArrayReceiveDoubleArrayRequest Request;
typedef SendDoubleArrayReceiveDoubleArrayResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SendDoubleArrayReceiveDoubleArray
} // namespace common_msgs_gl


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::common_msgs_gl::SendDoubleArrayReceiveDoubleArray > {
  static const char* value()
  {
    return "cf5053d681e2a2bc33c6323af1d83e31";
  }

  static const char* value(const ::common_msgs_gl::SendDoubleArrayReceiveDoubleArray&) { return value(); }
};

template<>
struct DataType< ::common_msgs_gl::SendDoubleArrayReceiveDoubleArray > {
  static const char* value()
  {
    return "common_msgs_gl/SendDoubleArrayReceiveDoubleArray";
  }

  static const char* value(const ::common_msgs_gl::SendDoubleArrayReceiveDoubleArray&) { return value(); }
};


// service_traits::MD5Sum< ::common_msgs_gl::SendDoubleArrayReceiveDoubleArrayRequest> should match 
// service_traits::MD5Sum< ::common_msgs_gl::SendDoubleArrayReceiveDoubleArray > 
template<>
struct MD5Sum< ::common_msgs_gl::SendDoubleArrayReceiveDoubleArrayRequest>
{
  static const char* value()
  {
    return MD5Sum< ::common_msgs_gl::SendDoubleArrayReceiveDoubleArray >::value();
  }
  static const char* value(const ::common_msgs_gl::SendDoubleArrayReceiveDoubleArrayRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::common_msgs_gl::SendDoubleArrayReceiveDoubleArrayRequest> should match 
// service_traits::DataType< ::common_msgs_gl::SendDoubleArrayReceiveDoubleArray > 
template<>
struct DataType< ::common_msgs_gl::SendDoubleArrayReceiveDoubleArrayRequest>
{
  static const char* value()
  {
    return DataType< ::common_msgs_gl::SendDoubleArrayReceiveDoubleArray >::value();
  }
  static const char* value(const ::common_msgs_gl::SendDoubleArrayReceiveDoubleArrayRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::common_msgs_gl::SendDoubleArrayReceiveDoubleArrayResponse> should match 
// service_traits::MD5Sum< ::common_msgs_gl::SendDoubleArrayReceiveDoubleArray > 
template<>
struct MD5Sum< ::common_msgs_gl::SendDoubleArrayReceiveDoubleArrayResponse>
{
  static const char* value()
  {
    return MD5Sum< ::common_msgs_gl::SendDoubleArrayReceiveDoubleArray >::value();
  }
  static const char* value(const ::common_msgs_gl::SendDoubleArrayReceiveDoubleArrayResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::common_msgs_gl::SendDoubleArrayReceiveDoubleArrayResponse> should match 
// service_traits::DataType< ::common_msgs_gl::SendDoubleArrayReceiveDoubleArray > 
template<>
struct DataType< ::common_msgs_gl::SendDoubleArrayReceiveDoubleArrayResponse>
{
  static const char* value()
  {
    return DataType< ::common_msgs_gl::SendDoubleArrayReceiveDoubleArray >::value();
  }
  static const char* value(const ::common_msgs_gl::SendDoubleArrayReceiveDoubleArrayResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // COMMON_MSGS_GL_MESSAGE_SENDDOUBLEARRAYRECEIVEDOUBLEARRAY_H
