// Generated by gencpp from file common_msgs_gl/SendBool.msg
// DO NOT EDIT!


#ifndef COMMON_MSGS_GL_MESSAGE_SENDBOOL_H
#define COMMON_MSGS_GL_MESSAGE_SENDBOOL_H

#include <ros/service_traits.h>


#include <common_msgs_gl/SendBoolRequest.h>
#include <common_msgs_gl/SendBoolResponse.h>


namespace common_msgs_gl
{

struct SendBool
{

typedef SendBoolRequest Request;
typedef SendBoolResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SendBool
} // namespace common_msgs_gl


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::common_msgs_gl::SendBool > {
  static const char* value()
  {
    return "8b94c1b53db61fb6aed406028ad6332a";
  }

  static const char* value(const ::common_msgs_gl::SendBool&) { return value(); }
};

template<>
struct DataType< ::common_msgs_gl::SendBool > {
  static const char* value()
  {
    return "common_msgs_gl/SendBool";
  }

  static const char* value(const ::common_msgs_gl::SendBool&) { return value(); }
};


// service_traits::MD5Sum< ::common_msgs_gl::SendBoolRequest> should match 
// service_traits::MD5Sum< ::common_msgs_gl::SendBool > 
template<>
struct MD5Sum< ::common_msgs_gl::SendBoolRequest>
{
  static const char* value()
  {
    return MD5Sum< ::common_msgs_gl::SendBool >::value();
  }
  static const char* value(const ::common_msgs_gl::SendBoolRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::common_msgs_gl::SendBoolRequest> should match 
// service_traits::DataType< ::common_msgs_gl::SendBool > 
template<>
struct DataType< ::common_msgs_gl::SendBoolRequest>
{
  static const char* value()
  {
    return DataType< ::common_msgs_gl::SendBool >::value();
  }
  static const char* value(const ::common_msgs_gl::SendBoolRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::common_msgs_gl::SendBoolResponse> should match 
// service_traits::MD5Sum< ::common_msgs_gl::SendBool > 
template<>
struct MD5Sum< ::common_msgs_gl::SendBoolResponse>
{
  static const char* value()
  {
    return MD5Sum< ::common_msgs_gl::SendBool >::value();
  }
  static const char* value(const ::common_msgs_gl::SendBoolResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::common_msgs_gl::SendBoolResponse> should match 
// service_traits::DataType< ::common_msgs_gl::SendBool > 
template<>
struct DataType< ::common_msgs_gl::SendBoolResponse>
{
  static const char* value()
  {
    return DataType< ::common_msgs_gl::SendBool >::value();
  }
  static const char* value(const ::common_msgs_gl::SendBoolResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // COMMON_MSGS_GL_MESSAGE_SENDBOOL_H
