// Generated by gencpp from file common_msgs_gl/SetOrientation.msg
// DO NOT EDIT!


#ifndef COMMON_MSGS_GL_MESSAGE_SETORIENTATION_H
#define COMMON_MSGS_GL_MESSAGE_SETORIENTATION_H

#include <ros/service_traits.h>


#include <common_msgs_gl/SetOrientationRequest.h>
#include <common_msgs_gl/SetOrientationResponse.h>


namespace common_msgs_gl
{

struct SetOrientation
{

typedef SetOrientationRequest Request;
typedef SetOrientationResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetOrientation
} // namespace common_msgs_gl


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::common_msgs_gl::SetOrientation > {
  static const char* value()
  {
    return "8ed1de3b69473461225107f55ad59b9d";
  }

  static const char* value(const ::common_msgs_gl::SetOrientation&) { return value(); }
};

template<>
struct DataType< ::common_msgs_gl::SetOrientation > {
  static const char* value()
  {
    return "common_msgs_gl/SetOrientation";
  }

  static const char* value(const ::common_msgs_gl::SetOrientation&) { return value(); }
};


// service_traits::MD5Sum< ::common_msgs_gl::SetOrientationRequest> should match 
// service_traits::MD5Sum< ::common_msgs_gl::SetOrientation > 
template<>
struct MD5Sum< ::common_msgs_gl::SetOrientationRequest>
{
  static const char* value()
  {
    return MD5Sum< ::common_msgs_gl::SetOrientation >::value();
  }
  static const char* value(const ::common_msgs_gl::SetOrientationRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::common_msgs_gl::SetOrientationRequest> should match 
// service_traits::DataType< ::common_msgs_gl::SetOrientation > 
template<>
struct DataType< ::common_msgs_gl::SetOrientationRequest>
{
  static const char* value()
  {
    return DataType< ::common_msgs_gl::SetOrientation >::value();
  }
  static const char* value(const ::common_msgs_gl::SetOrientationRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::common_msgs_gl::SetOrientationResponse> should match 
// service_traits::MD5Sum< ::common_msgs_gl::SetOrientation > 
template<>
struct MD5Sum< ::common_msgs_gl::SetOrientationResponse>
{
  static const char* value()
  {
    return MD5Sum< ::common_msgs_gl::SetOrientation >::value();
  }
  static const char* value(const ::common_msgs_gl::SetOrientationResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::common_msgs_gl::SetOrientationResponse> should match 
// service_traits::DataType< ::common_msgs_gl::SetOrientation > 
template<>
struct DataType< ::common_msgs_gl::SetOrientationResponse>
{
  static const char* value()
  {
    return DataType< ::common_msgs_gl::SetOrientation >::value();
  }
  static const char* value(const ::common_msgs_gl::SetOrientationResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // COMMON_MSGS_GL_MESSAGE_SETORIENTATION_H
