// Generated by gencpp from file common_msgs_gl/SetPosition.msg
// DO NOT EDIT!


#ifndef COMMON_MSGS_GL_MESSAGE_SETPOSITION_H
#define COMMON_MSGS_GL_MESSAGE_SETPOSITION_H

#include <ros/service_traits.h>


#include <common_msgs_gl/SetPositionRequest.h>
#include <common_msgs_gl/SetPositionResponse.h>


namespace common_msgs_gl
{

struct SetPosition
{

typedef SetPositionRequest Request;
typedef SetPositionResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetPosition
} // namespace common_msgs_gl


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::common_msgs_gl::SetPosition > {
  static const char* value()
  {
    return "e7bb0ef028c744b081acdc57743b11d8";
  }

  static const char* value(const ::common_msgs_gl::SetPosition&) { return value(); }
};

template<>
struct DataType< ::common_msgs_gl::SetPosition > {
  static const char* value()
  {
    return "common_msgs_gl/SetPosition";
  }

  static const char* value(const ::common_msgs_gl::SetPosition&) { return value(); }
};


// service_traits::MD5Sum< ::common_msgs_gl::SetPositionRequest> should match 
// service_traits::MD5Sum< ::common_msgs_gl::SetPosition > 
template<>
struct MD5Sum< ::common_msgs_gl::SetPositionRequest>
{
  static const char* value()
  {
    return MD5Sum< ::common_msgs_gl::SetPosition >::value();
  }
  static const char* value(const ::common_msgs_gl::SetPositionRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::common_msgs_gl::SetPositionRequest> should match 
// service_traits::DataType< ::common_msgs_gl::SetPosition > 
template<>
struct DataType< ::common_msgs_gl::SetPositionRequest>
{
  static const char* value()
  {
    return DataType< ::common_msgs_gl::SetPosition >::value();
  }
  static const char* value(const ::common_msgs_gl::SetPositionRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::common_msgs_gl::SetPositionResponse> should match 
// service_traits::MD5Sum< ::common_msgs_gl::SetPosition > 
template<>
struct MD5Sum< ::common_msgs_gl::SetPositionResponse>
{
  static const char* value()
  {
    return MD5Sum< ::common_msgs_gl::SetPosition >::value();
  }
  static const char* value(const ::common_msgs_gl::SetPositionResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::common_msgs_gl::SetPositionResponse> should match 
// service_traits::DataType< ::common_msgs_gl::SetPosition > 
template<>
struct DataType< ::common_msgs_gl::SetPositionResponse>
{
  static const char* value()
  {
    return DataType< ::common_msgs_gl::SetPosition >::value();
  }
  static const char* value(const ::common_msgs_gl::SetPositionResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // COMMON_MSGS_GL_MESSAGE_SETPOSITION_H
