// Generated by gencpp from file common_msgs_gl/SetPose.msg
// DO NOT EDIT!


#ifndef COMMON_MSGS_GL_MESSAGE_SETPOSE_H
#define COMMON_MSGS_GL_MESSAGE_SETPOSE_H

#include <ros/service_traits.h>


#include <common_msgs_gl/SetPoseRequest.h>
#include <common_msgs_gl/SetPoseResponse.h>


namespace common_msgs_gl
{

struct SetPose
{

typedef SetPoseRequest Request;
typedef SetPoseResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetPose
} // namespace common_msgs_gl


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::common_msgs_gl::SetPose > {
  static const char* value()
  {
    return "f192399f711a48924df9a394d37edd67";
  }

  static const char* value(const ::common_msgs_gl::SetPose&) { return value(); }
};

template<>
struct DataType< ::common_msgs_gl::SetPose > {
  static const char* value()
  {
    return "common_msgs_gl/SetPose";
  }

  static const char* value(const ::common_msgs_gl::SetPose&) { return value(); }
};


// service_traits::MD5Sum< ::common_msgs_gl::SetPoseRequest> should match 
// service_traits::MD5Sum< ::common_msgs_gl::SetPose > 
template<>
struct MD5Sum< ::common_msgs_gl::SetPoseRequest>
{
  static const char* value()
  {
    return MD5Sum< ::common_msgs_gl::SetPose >::value();
  }
  static const char* value(const ::common_msgs_gl::SetPoseRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::common_msgs_gl::SetPoseRequest> should match 
// service_traits::DataType< ::common_msgs_gl::SetPose > 
template<>
struct DataType< ::common_msgs_gl::SetPoseRequest>
{
  static const char* value()
  {
    return DataType< ::common_msgs_gl::SetPose >::value();
  }
  static const char* value(const ::common_msgs_gl::SetPoseRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::common_msgs_gl::SetPoseResponse> should match 
// service_traits::MD5Sum< ::common_msgs_gl::SetPose > 
template<>
struct MD5Sum< ::common_msgs_gl::SetPoseResponse>
{
  static const char* value()
  {
    return MD5Sum< ::common_msgs_gl::SetPose >::value();
  }
  static const char* value(const ::common_msgs_gl::SetPoseResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::common_msgs_gl::SetPoseResponse> should match 
// service_traits::DataType< ::common_msgs_gl::SetPose > 
template<>
struct DataType< ::common_msgs_gl::SetPoseResponse>
{
  static const char* value()
  {
    return DataType< ::common_msgs_gl::SetPose >::value();
  }
  static const char* value(const ::common_msgs_gl::SetPoseResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // COMMON_MSGS_GL_MESSAGE_SETPOSE_H
