// Generated by gencpp from file openhand/MoveServos.msg
// DO NOT EDIT!


#ifndef OPENHAND_MESSAGE_MOVESERVOS_H
#define OPENHAND_MESSAGE_MOVESERVOS_H

#include <ros/service_traits.h>


#include <openhand/MoveServosRequest.h>
#include <openhand/MoveServosResponse.h>


namespace openhand
{

struct MoveServos
{

typedef MoveServosRequest Request;
typedef MoveServosResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct MoveServos
} // namespace openhand


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::openhand::MoveServos > {
  static const char* value()
  {
    return "183031e0becb89936a926d61b84a7478";
  }

  static const char* value(const ::openhand::MoveServos&) { return value(); }
};

template<>
struct DataType< ::openhand::MoveServos > {
  static const char* value()
  {
    return "openhand/MoveServos";
  }

  static const char* value(const ::openhand::MoveServos&) { return value(); }
};


// service_traits::MD5Sum< ::openhand::MoveServosRequest> should match 
// service_traits::MD5Sum< ::openhand::MoveServos > 
template<>
struct MD5Sum< ::openhand::MoveServosRequest>
{
  static const char* value()
  {
    return MD5Sum< ::openhand::MoveServos >::value();
  }
  static const char* value(const ::openhand::MoveServosRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::openhand::MoveServosRequest> should match 
// service_traits::DataType< ::openhand::MoveServos > 
template<>
struct DataType< ::openhand::MoveServosRequest>
{
  static const char* value()
  {
    return DataType< ::openhand::MoveServos >::value();
  }
  static const char* value(const ::openhand::MoveServosRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::openhand::MoveServosResponse> should match 
// service_traits::MD5Sum< ::openhand::MoveServos > 
template<>
struct MD5Sum< ::openhand::MoveServosResponse>
{
  static const char* value()
  {
    return MD5Sum< ::openhand::MoveServos >::value();
  }
  static const char* value(const ::openhand::MoveServosResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::openhand::MoveServosResponse> should match 
// service_traits::DataType< ::openhand::MoveServos > 
template<>
struct DataType< ::openhand::MoveServosResponse>
{
  static const char* value()
  {
    return DataType< ::openhand::MoveServos >::value();
  }
  static const char* value(const ::openhand::MoveServosResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // OPENHAND_MESSAGE_MOVESERVOS_H
