// Generated by gencpp from file openhand/MoveServosRequest.msg
// DO NOT EDIT!


#ifndef OPENHAND_MESSAGE_MOVESERVOSREQUEST_H
#define OPENHAND_MESSAGE_MOVESERVOSREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace openhand
{
template <class ContainerAllocator>
struct MoveServosRequest_
{
  typedef MoveServosRequest_<ContainerAllocator> Type;

  MoveServosRequest_()
    : pos()  {
    }
  MoveServosRequest_(const ContainerAllocator& _alloc)
    : pos(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector<float, typename ContainerAllocator::template rebind<float>::other >  _pos_type;
  _pos_type pos;





  typedef boost::shared_ptr< ::openhand::MoveServosRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::openhand::MoveServosRequest_<ContainerAllocator> const> ConstPtr;

}; // struct MoveServosRequest_

typedef ::openhand::MoveServosRequest_<std::allocator<void> > MoveServosRequest;

typedef boost::shared_ptr< ::openhand::MoveServosRequest > MoveServosRequestPtr;
typedef boost::shared_ptr< ::openhand::MoveServosRequest const> MoveServosRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::openhand::MoveServosRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::openhand::MoveServosRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace openhand

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::openhand::MoveServosRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::openhand::MoveServosRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::openhand::MoveServosRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::openhand::MoveServosRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::openhand::MoveServosRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::openhand::MoveServosRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::openhand::MoveServosRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "2ddbdf76cbefd59cd9a914780fdf2963";
  }

  static const char* value(const ::openhand::MoveServosRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x2ddbdf76cbefd59cULL;
  static const uint64_t static_value2 = 0xd9a914780fdf2963ULL;
};

template<class ContainerAllocator>
struct DataType< ::openhand::MoveServosRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "openhand/MoveServosRequest";
  }

  static const char* value(const ::openhand::MoveServosRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::openhand::MoveServosRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32[] pos\n\
";
  }

  static const char* value(const ::openhand::MoveServosRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::openhand::MoveServosRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.pos);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct MoveServosRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::openhand::MoveServosRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::openhand::MoveServosRequest_<ContainerAllocator>& v)
  {
    s << indent << "pos[]" << std::endl;
    for (size_t i = 0; i < v.pos.size(); ++i)
    {
      s << indent << "  pos[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.pos[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // OPENHAND_MESSAGE_MOVESERVOSREQUEST_H
