// Generated by gencpp from file openhand/ReadServos.msg
// DO NOT EDIT!


#ifndef OPENHAND_MESSAGE_READSERVOS_H
#define OPENHAND_MESSAGE_READSERVOS_H

#include <ros/service_traits.h>


#include <openhand/ReadServosRequest.h>
#include <openhand/ReadServosResponse.h>


namespace openhand
{

struct ReadServos
{

typedef ReadServosRequest Request;
typedef ReadServosResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct ReadServos
} // namespace openhand


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::openhand::ReadServos > {
  static const char* value()
  {
    return "662e32bfc46f37715bb1455cf7d299a9";
  }

  static const char* value(const ::openhand::ReadServos&) { return value(); }
};

template<>
struct DataType< ::openhand::ReadServos > {
  static const char* value()
  {
    return "openhand/ReadServos";
  }

  static const char* value(const ::openhand::ReadServos&) { return value(); }
};


// service_traits::MD5Sum< ::openhand::ReadServosRequest> should match 
// service_traits::MD5Sum< ::openhand::ReadServos > 
template<>
struct MD5Sum< ::openhand::ReadServosRequest>
{
  static const char* value()
  {
    return MD5Sum< ::openhand::ReadServos >::value();
  }
  static const char* value(const ::openhand::ReadServosRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::openhand::ReadServosRequest> should match 
// service_traits::DataType< ::openhand::ReadServos > 
template<>
struct DataType< ::openhand::ReadServosRequest>
{
  static const char* value()
  {
    return DataType< ::openhand::ReadServos >::value();
  }
  static const char* value(const ::openhand::ReadServosRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::openhand::ReadServosResponse> should match 
// service_traits::MD5Sum< ::openhand::ReadServos > 
template<>
struct MD5Sum< ::openhand::ReadServosResponse>
{
  static const char* value()
  {
    return MD5Sum< ::openhand::ReadServos >::value();
  }
  static const char* value(const ::openhand::ReadServosResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::openhand::ReadServosResponse> should match 
// service_traits::DataType< ::openhand::ReadServos > 
template<>
struct DataType< ::openhand::ReadServosResponse>
{
  static const char* value()
  {
    return DataType< ::openhand::ReadServos >::value();
  }
  static const char* value(const ::openhand::ReadServosResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // OPENHAND_MESSAGE_READSERVOS_H
