// Generated by gencpp from file openhand/ReadLoadResponse.msg
// DO NOT EDIT!


#ifndef OPENHAND_MESSAGE_READLOADRESPONSE_H
#define OPENHAND_MESSAGE_READLOADRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace openhand
{
template <class ContainerAllocator>
struct ReadLoadResponse_
{
  typedef ReadLoadResponse_<ContainerAllocator> Type;

  ReadLoadResponse_()
    : load()  {
    }
  ReadLoadResponse_(const ContainerAllocator& _alloc)
    : load(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector<float, typename ContainerAllocator::template rebind<float>::other >  _load_type;
  _load_type load;





  typedef boost::shared_ptr< ::openhand::ReadLoadResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::openhand::ReadLoadResponse_<ContainerAllocator> const> ConstPtr;

}; // struct ReadLoadResponse_

typedef ::openhand::ReadLoadResponse_<std::allocator<void> > ReadLoadResponse;

typedef boost::shared_ptr< ::openhand::ReadLoadResponse > ReadLoadResponsePtr;
typedef boost::shared_ptr< ::openhand::ReadLoadResponse const> ReadLoadResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::openhand::ReadLoadResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::openhand::ReadLoadResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace openhand

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::openhand::ReadLoadResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::openhand::ReadLoadResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::openhand::ReadLoadResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::openhand::ReadLoadResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::openhand::ReadLoadResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::openhand::ReadLoadResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::openhand::ReadLoadResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "484bc5de2725aa512e1b0578d3e540c4";
  }

  static const char* value(const ::openhand::ReadLoadResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x484bc5de2725aa51ULL;
  static const uint64_t static_value2 = 0x2e1b0578d3e540c4ULL;
};

template<class ContainerAllocator>
struct DataType< ::openhand::ReadLoadResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "openhand/ReadLoadResponse";
  }

  static const char* value(const ::openhand::ReadLoadResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::openhand::ReadLoadResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32[] load\n\
\n\
";
  }

  static const char* value(const ::openhand::ReadLoadResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::openhand::ReadLoadResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.load);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ReadLoadResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::openhand::ReadLoadResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::openhand::ReadLoadResponse_<ContainerAllocator>& v)
  {
    s << indent << "load[]" << std::endl;
    for (size_t i = 0; i < v.load.size(); ++i)
    {
      s << indent << "  load[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.load[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // OPENHAND_MESSAGE_READLOADRESPONSE_H
