// Generated by gencpp from file openhand/ReadCurrentResponse.msg
// DO NOT EDIT!


#ifndef OPENHAND_MESSAGE_READCURRENTRESPONSE_H
#define OPENHAND_MESSAGE_READCURRENTRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace openhand
{
template <class ContainerAllocator>
struct ReadCurrentResponse_
{
  typedef ReadCurrentResponse_<ContainerAllocator> Type;

  ReadCurrentResponse_()
    : curr()  {
    }
  ReadCurrentResponse_(const ContainerAllocator& _alloc)
    : curr(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector<float, typename ContainerAllocator::template rebind<float>::other >  _curr_type;
  _curr_type curr;





  typedef boost::shared_ptr< ::openhand::ReadCurrentResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::openhand::ReadCurrentResponse_<ContainerAllocator> const> ConstPtr;

}; // struct ReadCurrentResponse_

typedef ::openhand::ReadCurrentResponse_<std::allocator<void> > ReadCurrentResponse;

typedef boost::shared_ptr< ::openhand::ReadCurrentResponse > ReadCurrentResponsePtr;
typedef boost::shared_ptr< ::openhand::ReadCurrentResponse const> ReadCurrentResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::openhand::ReadCurrentResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::openhand::ReadCurrentResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace openhand

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::openhand::ReadCurrentResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::openhand::ReadCurrentResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::openhand::ReadCurrentResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::openhand::ReadCurrentResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::openhand::ReadCurrentResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::openhand::ReadCurrentResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::openhand::ReadCurrentResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "640c8d4d28b8ccb823cd749d0957df5a";
  }

  static const char* value(const ::openhand::ReadCurrentResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x640c8d4d28b8ccb8ULL;
  static const uint64_t static_value2 = 0x23cd749d0957df5aULL;
};

template<class ContainerAllocator>
struct DataType< ::openhand::ReadCurrentResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "openhand/ReadCurrentResponse";
  }

  static const char* value(const ::openhand::ReadCurrentResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::openhand::ReadCurrentResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32[] curr\n\
\n\
";
  }

  static const char* value(const ::openhand::ReadCurrentResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::openhand::ReadCurrentResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.curr);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ReadCurrentResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::openhand::ReadCurrentResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::openhand::ReadCurrentResponse_<ContainerAllocator>& v)
  {
    s << indent << "curr[]" << std::endl;
    for (size_t i = 0; i < v.curr.size(); ++i)
    {
      s << indent << "  curr[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.curr[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // OPENHAND_MESSAGE_READCURRENTRESPONSE_H
