// Generated by gencpp from file openhand/ReadCurrent.msg
// DO NOT EDIT!


#ifndef OPENHAND_MESSAGE_READCURRENT_H
#define OPENHAND_MESSAGE_READCURRENT_H

#include <ros/service_traits.h>


#include <openhand/ReadCurrentRequest.h>
#include <openhand/ReadCurrentResponse.h>


namespace openhand
{

struct ReadCurrent
{

typedef ReadCurrentRequest Request;
typedef ReadCurrentResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct ReadCurrent
} // namespace openhand


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::openhand::ReadCurrent > {
  static const char* value()
  {
    return "640c8d4d28b8ccb823cd749d0957df5a";
  }

  static const char* value(const ::openhand::ReadCurrent&) { return value(); }
};

template<>
struct DataType< ::openhand::ReadCurrent > {
  static const char* value()
  {
    return "openhand/ReadCurrent";
  }

  static const char* value(const ::openhand::ReadCurrent&) { return value(); }
};


// service_traits::MD5Sum< ::openhand::ReadCurrentRequest> should match 
// service_traits::MD5Sum< ::openhand::ReadCurrent > 
template<>
struct MD5Sum< ::openhand::ReadCurrentRequest>
{
  static const char* value()
  {
    return MD5Sum< ::openhand::ReadCurrent >::value();
  }
  static const char* value(const ::openhand::ReadCurrentRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::openhand::ReadCurrentRequest> should match 
// service_traits::DataType< ::openhand::ReadCurrent > 
template<>
struct DataType< ::openhand::ReadCurrentRequest>
{
  static const char* value()
  {
    return DataType< ::openhand::ReadCurrent >::value();
  }
  static const char* value(const ::openhand::ReadCurrentRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::openhand::ReadCurrentResponse> should match 
// service_traits::MD5Sum< ::openhand::ReadCurrent > 
template<>
struct MD5Sum< ::openhand::ReadCurrentResponse>
{
  static const char* value()
  {
    return MD5Sum< ::openhand::ReadCurrent >::value();
  }
  static const char* value(const ::openhand::ReadCurrentResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::openhand::ReadCurrentResponse> should match 
// service_traits::DataType< ::openhand::ReadCurrent > 
template<>
struct DataType< ::openhand::ReadCurrentResponse>
{
  static const char* value()
  {
    return DataType< ::openhand::ReadCurrent >::value();
  }
  static const char* value(const ::openhand::ReadCurrentResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // OPENHAND_MESSAGE_READCURRENT_H
