// Generated by gencpp from file openhand/ReadTemperatureResponse.msg
// DO NOT EDIT!


#ifndef OPENHAND_MESSAGE_READTEMPERATURERESPONSE_H
#define OPENHAND_MESSAGE_READTEMPERATURERESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace openhand
{
template <class ContainerAllocator>
struct ReadTemperatureResponse_
{
  typedef ReadTemperatureResponse_<ContainerAllocator> Type;

  ReadTemperatureResponse_()
    : temp()  {
    }
  ReadTemperatureResponse_(const ContainerAllocator& _alloc)
    : temp(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector<float, typename ContainerAllocator::template rebind<float>::other >  _temp_type;
  _temp_type temp;





  typedef boost::shared_ptr< ::openhand::ReadTemperatureResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::openhand::ReadTemperatureResponse_<ContainerAllocator> const> ConstPtr;

}; // struct ReadTemperatureResponse_

typedef ::openhand::ReadTemperatureResponse_<std::allocator<void> > ReadTemperatureResponse;

typedef boost::shared_ptr< ::openhand::ReadTemperatureResponse > ReadTemperatureResponsePtr;
typedef boost::shared_ptr< ::openhand::ReadTemperatureResponse const> ReadTemperatureResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::openhand::ReadTemperatureResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::openhand::ReadTemperatureResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace openhand

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::openhand::ReadTemperatureResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::openhand::ReadTemperatureResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::openhand::ReadTemperatureResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::openhand::ReadTemperatureResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::openhand::ReadTemperatureResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::openhand::ReadTemperatureResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::openhand::ReadTemperatureResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "52444e69c3eaa80dd939a5bad6dbe319";
  }

  static const char* value(const ::openhand::ReadTemperatureResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x52444e69c3eaa80dULL;
  static const uint64_t static_value2 = 0xd939a5bad6dbe319ULL;
};

template<class ContainerAllocator>
struct DataType< ::openhand::ReadTemperatureResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "openhand/ReadTemperatureResponse";
  }

  static const char* value(const ::openhand::ReadTemperatureResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::openhand::ReadTemperatureResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32[] temp\n\
\n\
";
  }

  static const char* value(const ::openhand::ReadTemperatureResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::openhand::ReadTemperatureResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.temp);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ReadTemperatureResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::openhand::ReadTemperatureResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::openhand::ReadTemperatureResponse_<ContainerAllocator>& v)
  {
    s << indent << "temp[]" << std::endl;
    for (size_t i = 0; i < v.temp.size(); ++i)
    {
      s << indent << "  temp[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.temp[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // OPENHAND_MESSAGE_READTEMPERATURERESPONSE_H
