// Generated by gencpp from file openhand/ReadTemperature.msg
// DO NOT EDIT!


#ifndef OPENHAND_MESSAGE_READTEMPERATURE_H
#define OPENHAND_MESSAGE_READTEMPERATURE_H

#include <ros/service_traits.h>


#include <openhand/ReadTemperatureRequest.h>
#include <openhand/ReadTemperatureResponse.h>


namespace openhand
{

struct ReadTemperature
{

typedef ReadTemperatureRequest Request;
typedef ReadTemperatureResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct ReadTemperature
} // namespace openhand


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::openhand::ReadTemperature > {
  static const char* value()
  {
    return "52444e69c3eaa80dd939a5bad6dbe319";
  }

  static const char* value(const ::openhand::ReadTemperature&) { return value(); }
};

template<>
struct DataType< ::openhand::ReadTemperature > {
  static const char* value()
  {
    return "openhand/ReadTemperature";
  }

  static const char* value(const ::openhand::ReadTemperature&) { return value(); }
};


// service_traits::MD5Sum< ::openhand::ReadTemperatureRequest> should match 
// service_traits::MD5Sum< ::openhand::ReadTemperature > 
template<>
struct MD5Sum< ::openhand::ReadTemperatureRequest>
{
  static const char* value()
  {
    return MD5Sum< ::openhand::ReadTemperature >::value();
  }
  static const char* value(const ::openhand::ReadTemperatureRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::openhand::ReadTemperatureRequest> should match 
// service_traits::DataType< ::openhand::ReadTemperature > 
template<>
struct DataType< ::openhand::ReadTemperatureRequest>
{
  static const char* value()
  {
    return DataType< ::openhand::ReadTemperature >::value();
  }
  static const char* value(const ::openhand::ReadTemperatureRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::openhand::ReadTemperatureResponse> should match 
// service_traits::MD5Sum< ::openhand::ReadTemperature > 
template<>
struct MD5Sum< ::openhand::ReadTemperatureResponse>
{
  static const char* value()
  {
    return MD5Sum< ::openhand::ReadTemperature >::value();
  }
  static const char* value(const ::openhand::ReadTemperatureResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::openhand::ReadTemperatureResponse> should match 
// service_traits::DataType< ::openhand::ReadTemperature > 
template<>
struct DataType< ::openhand::ReadTemperatureResponse>
{
  static const char* value()
  {
    return DataType< ::openhand::ReadTemperature >::value();
  }
  static const char* value(const ::openhand::ReadTemperatureResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // OPENHAND_MESSAGE_READTEMPERATURE_H
