// Generated by gencpp from file gripper_nodes/CommandTrajectory.msg
// DO NOT EDIT!


#ifndef GRIPPER_NODES_MESSAGE_COMMANDTRAJECTORY_H
#define GRIPPER_NODES_MESSAGE_COMMANDTRAJECTORY_H

#include <ros/service_traits.h>


#include <gripper_nodes/CommandTrajectoryRequest.h>
#include <gripper_nodes/CommandTrajectoryResponse.h>


namespace gripper_nodes
{

struct CommandTrajectory
{

typedef CommandTrajectoryRequest Request;
typedef CommandTrajectoryResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct CommandTrajectory
} // namespace gripper_nodes


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::gripper_nodes::CommandTrajectory > {
  static const char* value()
  {
    return "0b7d86359979bf7cfc9d521b2deb7302";
  }

  static const char* value(const ::gripper_nodes::CommandTrajectory&) { return value(); }
};

template<>
struct DataType< ::gripper_nodes::CommandTrajectory > {
  static const char* value()
  {
    return "gripper_nodes/CommandTrajectory";
  }

  static const char* value(const ::gripper_nodes::CommandTrajectory&) { return value(); }
};


// service_traits::MD5Sum< ::gripper_nodes::CommandTrajectoryRequest> should match 
// service_traits::MD5Sum< ::gripper_nodes::CommandTrajectory > 
template<>
struct MD5Sum< ::gripper_nodes::CommandTrajectoryRequest>
{
  static const char* value()
  {
    return MD5Sum< ::gripper_nodes::CommandTrajectory >::value();
  }
  static const char* value(const ::gripper_nodes::CommandTrajectoryRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::gripper_nodes::CommandTrajectoryRequest> should match 
// service_traits::DataType< ::gripper_nodes::CommandTrajectory > 
template<>
struct DataType< ::gripper_nodes::CommandTrajectoryRequest>
{
  static const char* value()
  {
    return DataType< ::gripper_nodes::CommandTrajectory >::value();
  }
  static const char* value(const ::gripper_nodes::CommandTrajectoryRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::gripper_nodes::CommandTrajectoryResponse> should match 
// service_traits::MD5Sum< ::gripper_nodes::CommandTrajectory > 
template<>
struct MD5Sum< ::gripper_nodes::CommandTrajectoryResponse>
{
  static const char* value()
  {
    return MD5Sum< ::gripper_nodes::CommandTrajectory >::value();
  }
  static const char* value(const ::gripper_nodes::CommandTrajectoryResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::gripper_nodes::CommandTrajectoryResponse> should match 
// service_traits::DataType< ::gripper_nodes::CommandTrajectory > 
template<>
struct DataType< ::gripper_nodes::CommandTrajectoryResponse>
{
  static const char* value()
  {
    return DataType< ::gripper_nodes::CommandTrajectory >::value();
  }
  static const char* value(const ::gripper_nodes::CommandTrajectoryResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // GRIPPER_NODES_MESSAGE_COMMANDTRAJECTORY_H
