// Generated by gencpp from file gripper_nodes/CommandTrajectoryResponse.msg
// DO NOT EDIT!


#ifndef GRIPPER_NODES_MESSAGE_COMMANDTRAJECTORYRESPONSE_H
#define GRIPPER_NODES_MESSAGE_COMMANDTRAJECTORYRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace gripper_nodes
{
template <class ContainerAllocator>
struct CommandTrajectoryResponse_
{
  typedef CommandTrajectoryResponse_<ContainerAllocator> Type;

  CommandTrajectoryResponse_()
    {
    }
  CommandTrajectoryResponse_(const ContainerAllocator& _alloc)
    {
  (void)_alloc;
    }







  typedef boost::shared_ptr< ::gripper_nodes::CommandTrajectoryResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::gripper_nodes::CommandTrajectoryResponse_<ContainerAllocator> const> ConstPtr;

}; // struct CommandTrajectoryResponse_

typedef ::gripper_nodes::CommandTrajectoryResponse_<std::allocator<void> > CommandTrajectoryResponse;

typedef boost::shared_ptr< ::gripper_nodes::CommandTrajectoryResponse > CommandTrajectoryResponsePtr;
typedef boost::shared_ptr< ::gripper_nodes::CommandTrajectoryResponse const> CommandTrajectoryResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::gripper_nodes::CommandTrajectoryResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::gripper_nodes::CommandTrajectoryResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace gripper_nodes

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::gripper_nodes::CommandTrajectoryResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::gripper_nodes::CommandTrajectoryResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::gripper_nodes::CommandTrajectoryResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::gripper_nodes::CommandTrajectoryResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::gripper_nodes::CommandTrajectoryResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::gripper_nodes::CommandTrajectoryResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::gripper_nodes::CommandTrajectoryResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const ::gripper_nodes::CommandTrajectoryResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::gripper_nodes::CommandTrajectoryResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "gripper_nodes/CommandTrajectoryResponse";
  }

  static const char* value(const ::gripper_nodes::CommandTrajectoryResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::gripper_nodes::CommandTrajectoryResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n\
";
  }

  static const char* value(const ::gripper_nodes::CommandTrajectoryResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::gripper_nodes::CommandTrajectoryResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream&, T)
    {}

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct CommandTrajectoryResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::gripper_nodes::CommandTrajectoryResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream&, const std::string&, const ::gripper_nodes::CommandTrajectoryResponse_<ContainerAllocator>&)
  {}
};

} // namespace message_operations
} // namespace ros

#endif // GRIPPER_NODES_MESSAGE_COMMANDTRAJECTORYRESPONSE_H
